server:
  # 端口
  port: 8080

spring:
  application:
    name: universityhelper
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/universityhelper?serverTimezone=UTC
    username: root
    password: 123456
    # 数据库类型
    type: com.alibaba.druid.pool.DruidDataSource
    name: defaultDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    # mybatis-plus操作日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # Mapper文件
  mapper-locations: classpath*:mapper/*xml
  # 实体目录
  type-aliases-package: com.yhm.universityhelper.entity.po
  # mybatis-plus全局配置
  global-config:
    db-config:
      #配置MyBatis-Plus的主键策略
      id-type: auto

authentication:
  jwt:
    header: Authorization
    expire: 604800
    secret: UniversityHelper

account:
  locked:
    max-failed-attempts: 5
    lock-time: 30